<?php
/**
 * CrowdSec_Engine Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Engine
 * @copyright  Copyright (c)  2023+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Engine
 * @module   Engine
 * @author   CrowdSec team
 *
 */

/** @var \CrowdSec\Engine\Block\Adminhtml\Report\Metrics $block */
?>

<?php
  $origins = $block->getOriginsCount();
?>

<div id="crowdsec-engine-remediation-metrics" >
    <h2 class="crowdsec-engine-report-subtitle"><?= $block->escapeHtml(__('Metrics')) ?></h2>
    <div class="description">
        <h3><?= $block->escapeHtml(__('Current bouncing behaviors')) ?></h3>
        <ul>
            <li>&bull;
                <?php if ($block->isLocalBanEnabled()): ?>
                    <?=
                    $block->escapeHtml(
                        __('<i>Ban IP locally</i> setting is <b>enabled</b>
&rarr; When a Magento scenario triggers an alert, IP <b>is banned</b> locally.'),
                        ['i','a','b']
                    )
                    ?>
                <?php else: ?>
                    <?=
                    $block->escapeHtml(
                        __('<i>Ban IP locally</i> setting is <b>disabled</b>
&rarr; When a Magento scenario triggers an alert, IP <b>is not banned locally</b>.'),
                        ['i','a','b']
                    ) ?>
                <?php endif; ?>
            </li>
            <li>&bull;
                <?php if ($block->isBanBouncingEnabled()): ?>
                    <?=
                    $block->escapeHtml(
                        __('<i>Block banned IP</i> setting is <b>enabled</b>
&rarr; Access is currently <b>blocked</b> for banned IP addresses.'),
                        ['i','a','b']
                    ) ?>
                <?php else: ?>
                    <?=
                    $block->escapeHtml(
                        __('<i>Block banned IP</i> setting is <b>disabled</b>
&rarr; Access is currently <b>allowed</b> for banned IP addresses.'),
                        ['i','a','b']
                    ) ?>
                <?php endif; ?>
            </li>
            <li>&bull;
                <?=
                $block->escapeHtml(
                    __(
                        '<i>Fallback</i> setting is <b>%1</b>
&rarr; Any remediation that differs from "ban" will be considered as a <b>%1</b> remediation.',
                        $block->getFallback()
                    ),
                    ['i','a','b']
                ) ?>
            </li>
        </ul>
        <p class="notice"><?= $block->escapeHtml(__(
            'You can change these behaviors by modifying decisions settings <a href="%1">here</a>.',
            $block->getSettingsUrl() .'#crowdsec_engine_decisions-link'
        ), ['i','a','b'])
?></p>
    </div>
    <div class="description">
        <h3><?= $block->escapeHtml(__('Decision metrics')) ?><sup>(1)</sup></h3>
    </div>

    <div class="admin_data-grid-wrap">
        <table id="crowdsec-engine-metrics" class="data-grid">
            <thead>
                <th class="data_grid-th">
                    <span class="data-grid-cell-content"><?= $block->escapeHtml(__('Origin of the decision')) ?></span>
                </th>
                <th class="data_grid-th">
                    <span class="data-grid-cell-content"><?= $block->escapeHtml(__('Count')) ?></span>
                </th>
            </thead>
            <tbody>
                <tr class="data-row">
                    <td class="origin"><?= $block->escapeHtml(__('CrowdSec Engine extension (Local decision)')) ?></td>
                    <td class="count"><?= $block->escapeHtml($origins[$block->getOriginCrowdsec()] ?? 0) ?></td>
                </tr>
                <tr class="data-row">
                    <td class="origin"><?= $block->escapeHtml(__('CrowdSec Community blocklist')) ?></td>
                    <td class="count"><?= $block->escapeHtml($origins[$block->getOriginCapi()] ?? 0) ?></td>
                </tr>
                <tr class="data-row">
                    <td class="origin"><?= $block->escapeHtml(__('Subscribed third-party blocklists')) ?></td>
                    <td class="count"><?= $block->escapeHtml($origins[$block->getOriginLists()] ?? 0) ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div>
        <p><span>1. </span>
        <?= $block->escapeHtml(
            __('This module stores CrowdSec decision metricsonly if the <i>Block banned IP</i> setting is enabled.'),
            ['i']
        ) ?><br>
        <?=
        $block->escapeHtml(
            __('As this information is stored in cache,
                it will be reset if you clear the CrowdSec Engine cache.')
        )
        ?>
        </p>
    </div>
</div>


