<?php
/**
 * CrowdSec_Engine Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Engine
 * @copyright  Copyright (c)  2023+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Engine
 * @module   Engine
 * @author   CrowdSec team
 *
 */

/** @var \CrowdSec\Engine\Block\Adminhtml\System\Config\Signals\Push $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>

<?php

 $ajaxUrl = $escaper->escapeJs($block->getAjaxUrl());
 $errorMessage = $escaper->escapeJs($escaper->escapeHtml(__('Error during CrowdSec Signals push.')));

 $scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function pushSignals() {
        var pushSignalsMessage = $('signals_push_result');

        params = {};

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.pushed == 1) {
                        pushSignalsMessage.removeClassName('hidden')
                                .removeClassName('error').addClassName('success');
                    } else {
                        pushSignalsMessage.removeClassName('hidden').removeClassName('success')
                                .addClassName('error');
                    }
                } catch (e) {
                    pushSignalsMessage.removeClassName('hidden').removeClassName('success')
                            .addClassName('error');
                }
                pushSignalsMessage.update(result);
            }
        });
    }

    window.pushSignals = pushSignals;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-push-signals actions-crowdsec">
    <button class="action-push-signals" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="hidden" id="signals_push_result"></p>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#signals_push_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'pushSignals();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
