<?php
/**
 * CrowdSec_Engine Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Engine
 * @copyright  Copyright (c)  2023+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Engine
 * @module   Engine
 * @author   CrowdSec team
 *
 */

?>

<?php
/** @var \CrowdSec\Engine\Block\Adminhtml\System\Config\Enroll $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function enrollEngine() {
            var enrollEngineMessage = $('engine_enroll_result');

            params = {
                enroll_key: $('<?= $escaper->escapeJs($block->getEnrollKeyField()) ?>').value,
                engine_name: $('<?= $escaper->escapeJs($block->getEngineNameField()) ?>').value,
                force_enroll: $('<?= $escaper->escapeJs($block->getForceEnrollField()) ?>').value
            };

            new Ajax.Request('<?= $escaper->escapeJs($escaper->escapeUrl($block->getAjaxUrl())) ?>', {
                parameters: params,
                onSuccess: function(response) {
                    var result =
                        '<?= $escaper->escapeJs(
                            $escaper->escapeHtml(__('Error during CrowdSec engine enrollment.'))
                        ) ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.enrolled == 1) {
                            enrollEngineMessage.removeClassName('hidden')
                                .removeClassName('error').addClassName('success');
                        } else {
                            enrollEngineMessage.removeClassName('hidden').removeClassName('success')
                                .addClassName('error');
                        }
                    } catch (e) {
                        enrollEngineMessage.removeClassName('hidden').removeClassName('success')
                            .addClassName('error');
                    }
                    enrollEngineMessage.update(result);
                }
            });
        }

        window.enrollEngine = enrollEngine;
//]]>

    });
</script>

<div class="actions actions-enroll-engine actions-crowdsec">
    <button onclick="javascript:enrollEngine(); return false;" class="action-enroll-engine" type="button" id="<?=
    $escaper->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="hidden" id="engine_enroll_result"></p>
</div>

